services:
  assuranceservice:
    image: ghcr.io/yndinga/assuranceservice:${IMAGE_TAG:-1.1.0}
    container_name: assuranceservice
    ports:
      - "8087:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AssuranceConnection=${SQL_CONNECTION_STRING:-Server=192.168.3.178,1434;Database=MS_ASSURANCE;User ID=sa;Password=MonMotDePasseFort!;Connect Timeout=30;Encrypt=False;Trust Server Certificate=True;}
      - Consul__Host=192.168.2.89
      - Consul__Port=8500
      - Consul__ServiceName=AssuranceService
      - Consul__ServiceId=assurance-service-1
      - Consul__ServiceAddress=192.168.2.89
      - Consul__ServicePort=8087
      - Consul__HealthCheckPath=/health
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "sqlserver:host-gateway"
    restart: unless-stopped
