services:
  grafana:
    image: grafana/grafana:11.2.2
    container_name: obs-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - observability

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: obs-prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - observability

  loki:
    image: grafana/loki:3.1.1
    container_name: obs-loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - loki-data:/loki
      - ./loki/config.yml:/etc/loki/config.yml:ro
    networks:
      - observability

  promtail:
    image: grafana/promtail:3.1.1
    container_name: obs-promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      # Logs Docker (Linux). Sur Windows Docker Desktop, ce path peut varier.
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    depends_on:
      - loki
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.6.1
    container_name: obs-tempo
    ports:
      - "3200:3200"   # Tempo query
      - "4317:4317"   # OTLP gRPC (si tu veux envoyer direct Tempo)
      - "4318:4318"   # OTLP HTTP (si tu veux envoyer direct Tempo)
    command: ["-config.file=/etc/tempo/config.yml"]
    volumes:
      - tempo-data:/var/tempo
      - ./tempo/config.yml:/etc/tempo/config.yml:ro
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    container_name: obs-otel-collector
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus exporter (collector metrics)
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ./otel-collector/config.yml:/etc/otelcol/config.yml:ro
    depends_on:
      - tempo
    networks:
      - observability

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  tempo-data:

networks:
  observability:
    name: observability

