// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssuranceService.Infrastructure.Migrations
{
    [DbContext(typeof(AssuranceService.Infrastructure.Data.AssuranceDbContext))]
    partial class AssuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssuranceService.Application.Sagas.AssuranceProcessState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AssuranceCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("GarantiesAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("MarchandisesAdded")
                        .HasColumnType("bit");

                    b.Property<string>("NoPolice")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("PrimeCalculated")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Importateur")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CorrelationId");

                    b.ToTable("AssuranceProcessStates", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Aerien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AeroportDebarquement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AeroportEmbarquement")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Aeriens", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Assurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssureurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duree")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid?>("GarantieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IntermediaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImportateurNIU")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ImportateurNom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoPolice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroCert")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("OCRE")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("GarantieId");

                    b.HasIndex("NoPolice")
                        .IsUnique()
                        .HasFilter("[NoPolice] IS NOT NULL");

                    b.HasIndex("NumeroCert")
                        .IsUnique()
                        .HasFilter("[NumeroCert] IS NOT NULL");

                    b.ToTable("Assurances", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Cotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Accessoires")
                        .HasColumnType("float");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<double?>("PrimeNette")
                        .HasColumnType("float");

                    b.Property<double?>("PrimeTotale")
                        .HasColumnType("float");

                    b.Property<string>("Taux")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Taxe")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cotations", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Fluvial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PortDebarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortEmbarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortDebarquementId");

                    b.HasIndex("PortEmbarquementId");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Fluviaux", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Maritime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PortDebarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortEmbarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortDebarquementId");

                    b.HasIndex("PortEmbarquementId");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Maritimes", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Marchandise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Marque")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MasseBrute")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specificites")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniteStatistique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValeurFCFA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValeurDevise")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("Marchandises", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Prime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Accessoires")
                        .HasColumnType("float");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PrimeNette")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrimeTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taux")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Taxe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurFCFA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurDevise")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("Primes", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Routier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("RouteNationale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Routiers", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.VisaAssurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VisaContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisaOK")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("VisaAssurances", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Voyage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("DureeSejour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LieuSejour")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomNavire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomTransporteur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaysDestination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaysProvenance")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeNavire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.ToTable("Voyages", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Garantie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<decimal>("Accessoires")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomGarantie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Taux")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Garanties", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Aeroport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PaysId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaysId");

                    b.ToTable("Aeroports", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Corridor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Corridors", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Departement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departements", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Devise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Devises", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Pays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pays", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaysId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("PaysId");

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.TauxDeChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Taux")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("ValideDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviseId");

                    b.ToTable("TauxDeChanges", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Troncon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorridorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorridorId");

                    b.HasIndex("RouteId");

                    b.ToTable("Troncons", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Aerien", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Voyage", null)
                        .WithOne("Aerien")
                        .HasForeignKey("AssuranceService.Domain.Models.Aerien", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Assurance", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Garantie", null)
                        .WithMany()
                        .HasForeignKey("GarantieId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Fluvial", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", null)
                        .WithMany()
                        .HasForeignKey("PortDebarquementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", null)
                        .WithMany()
                        .HasForeignKey("PortEmbarquementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Voyage", null)
                        .WithOne("Fluvial")
                        .HasForeignKey("AssuranceService.Domain.Models.Fluvial", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Maritime", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", null)
                        .WithMany()
                        .HasForeignKey("PortDebarquementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", null)
                        .WithMany()
                        .HasForeignKey("PortEmbarquementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Voyage", null)
                        .WithOne("Maritime")
                        .HasForeignKey("AssuranceService.Domain.Models.Maritime", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Marchandise", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", null)
                        .WithMany("Marchandises")
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Prime", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", null)
                        .WithMany()
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Routier", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Voyage", null)
                        .WithOne("Routier")
                        .HasForeignKey("AssuranceService.Domain.Models.Routier", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.VisaAssurance", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", null)
                        .WithMany("Visas")
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Voyage", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", null)
                        .WithOne("Voyage")
                        .HasForeignKey("AssuranceService.Domain.Models.Voyage", "AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Module", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Aeroport", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Pays", null)
                        .WithMany()
                        .HasForeignKey("PaysId");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Port", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Pays", null)
                        .WithMany()
                        .HasForeignKey("PaysId");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.TauxDeChange", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Devise", null)
                        .WithMany()
                        .HasForeignKey("DeviseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Troncon", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Corridor", null)
                        .WithMany()
                        .HasForeignKey("CorridorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
