// <auto-generated />
using System;
using AssuranceService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssuranceService.Infrastructure.Migrations
{
    [DbContext(typeof(AssuranceDbContext))]
    partial class AssuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssuranceService.Application.Sagas.AssuranceProcessState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AssuranceCreated")
                        .HasColumnType("bit");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("GarantiesAssigned")
                        .HasColumnType("bit");

                    b.Property<string>("Importateur")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MarchandisesAdded")
                        .HasColumnType("bit");

                    b.Property<string>("NoPolice")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("PrimeCalculated")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CorrelationId");

                    b.ToTable("AssuranceProcessStates", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Aerien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AeroportDebarquement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AeroportEmbarquement")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Aeriens", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Assurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("AssureurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duree")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("GarantieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImportateurNIU")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImportateurNom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("IntermediaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NoPolice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroCert")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OCRE")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("10");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GarantieId");

                    b.HasIndex("NoPolice")
                        .IsUnique()
                        .HasFilter("[NoPolice] IS NOT NULL");

                    b.HasIndex("NumeroCert")
                        .IsUnique()
                        .HasFilter("[NumeroCert] IS NOT NULL");

                    b.ToTable("Assurances", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Cotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal?>("Accessoires")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ContratId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PartenaireId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("PrimeNette")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrimeTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StatutId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Taux")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Taxe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Cotations", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Taille")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Fluvial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PortDebarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortEmbarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortDebarquementId");

                    b.HasIndex("PortEmbarquementId");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Fluviaux", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Garantie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Accessoires")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NomGarantie");

                    b.Property<decimal?>("Taux")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Garanties", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Marchandise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssuranceId");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Devise");

                    b.Property<string>("Marque")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MasseBrute")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Specificites")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniteStatistique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ValeurDevise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurFCFA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("Marchandises", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Maritime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortDebarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortEmbarquementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortDebarquementId");

                    b.HasIndex("PortEmbarquementId");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Maritimes", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Prime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal?>("Accessoires")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssuranceId");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrimeNette")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrimeTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Statut");

                    b.Property<decimal?>("Taux")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Taxe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurDevise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurFCFA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("Primes", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Aeroport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PaysId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Aeroports");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Corridor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Corridors");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Departement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Devise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Devises");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Pays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaysId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.TauxDeChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Taux")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20, 5)");

                    b.Property<string>("ValideDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviseId");

                    b.ToTable("TauxDeChanges", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Troncon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorridorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Troncons");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.UniteStatistique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UniteStatistiques");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Routier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteNationale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VoyageId")
                        .IsUnique();

                    b.ToTable("Routiers", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Specificite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Specificites", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.TypeTransport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TypeTransports", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.VisaAssurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VisaContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisaOK")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId");

                    b.ToTable("VisaAssurances", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Voyage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AssuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreerLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreerPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DureeSejour")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LieuSejour")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NomNavire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomTransporteur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaysDestination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaysProvenance")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeNavire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssuranceId")
                        .IsUnique();

                    b.ToTable("Voyages", (string)null);
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Aerien", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Voyage", "Voyage")
                        .WithOne("Aerien")
                        .HasForeignKey("AssuranceService.Domain.Models.Aerien", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Assurance", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Garantie", "Garantie")
                        .WithMany()
                        .HasForeignKey("GarantieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Garantie");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Document", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", "Assurance")
                        .WithMany("Documents")
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assurance");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Fluvial", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", "PortDebarquement")
                        .WithMany()
                        .HasForeignKey("PortDebarquementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", "PortEmbarquement")
                        .WithMany()
                        .HasForeignKey("PortEmbarquementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Voyage", "Voyage")
                        .WithOne("Fluvial")
                        .HasForeignKey("AssuranceService.Domain.Models.Fluvial", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortDebarquement");

                    b.Navigation("PortEmbarquement");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Marchandise", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", "Assurance")
                        .WithMany("Marchandises")
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assurance");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Maritime", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", "PortDebarquement")
                        .WithMany()
                        .HasForeignKey("PortDebarquementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Port", "PortEmbarquement")
                        .WithMany()
                        .HasForeignKey("PortEmbarquementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssuranceService.Domain.Models.Voyage", "Voyage")
                        .WithOne("Maritime")
                        .HasForeignKey("AssuranceService.Domain.Models.Maritime", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortDebarquement");

                    b.Navigation("PortEmbarquement");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Prime", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", null)
                        .WithMany("Primes")
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.TauxDeChange", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Referentiel.Devise", "Devise")
                        .WithMany("TauxDeChanges")
                        .HasForeignKey("DeviseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devise");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Routier", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Voyage", "Voyage")
                        .WithOne("Routier")
                        .HasForeignKey("AssuranceService.Domain.Models.Routier", "VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.VisaAssurance", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", "Assurance")
                        .WithMany("Visas")
                        .HasForeignKey("AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assurance");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Voyage", b =>
                {
                    b.HasOne("AssuranceService.Domain.Models.Assurance", "Assurance")
                        .WithOne("Voyage")
                        .HasForeignKey("AssuranceService.Domain.Models.Voyage", "AssuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assurance");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Assurance", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Marchandises");

                    b.Navigation("Primes");

                    b.Navigation("Visas");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Referentiel.Devise", b =>
                {
                    b.Navigation("TauxDeChanges");
                });

            modelBuilder.Entity("AssuranceService.Domain.Models.Voyage", b =>
                {
                    b.Navigation("Aerien");

                    b.Navigation("Fluvial");

                    b.Navigation("Maritime");

                    b.Navigation("Routier");
                });
#pragma warning restore 612, 618
        }
    }
}
